version: "2"
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.0

    working_directory: /go/src/github/ofili/chatbot

    steps:
      - checkout
      - run:
          name: Get dependencies
          command: go get -v

      - run:
          name: Check code style
          command: go vet ./...